### PR TITLE
Add a command list to README.md

### PR DESCRIPTION
**Pull request by mattconsto**
No more need to consult the audio directory or the .go source files. For brevity I left out the alternative !commands.

### CODE REVIEW

**Comment by RBTDN** [comment]
I only know 2 Commands, and i really need thissss!!!!!!!!!!!!!

**Comment by IvanDelsinne** [comment]
This is what's needed, it should be added.

**Comment by MaxiBerdy** [comment]
I agree

**Comment by b1naryth1ef** [comment]
Thanks, but we're not looking to add this.

**Pull request closed without merging**
